FROM golang:1.11

RUN mkdir -p /usr/local/go/src/github.com/tenorbear/grpc-go-loadtest/server
RUN mkdir -p /usr/local/go/src/github.com/tenorbear/grpc-go-loadtest/helloworld

Add ./server /usr/local/go/src/github.com/tenorbear/grpc-go-loadtest/server
Add ./helloworld /usr/local/go/src/github.com/tenorbear/grpc-go-loadtest/helloworld

WORKDIR /usr/local/go/src/github.com/tenorbear/grpc-go-loadtest/server

RUN go get -d -v ./...

RUN go build

RUN ls

EXPOSE 50051

ENTRYPOINT ["./server"]
